version: "3"
services:
  mock-server:
    image: mock-server:latest
    ports:
      - "9011:9011"
    environment:
      JVM_OPTS: -server -Xms512m -Xmx512m
      MOCK_PORT: 9011
      INSTANCES: 2
#    links:
#      - local-mongo
#      - local-redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    networks:
      - devnet
networks:
  devnet:
    driver: bridge